/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#FFF5F7',
        bgSoft: '#FFF9FA',
        bgWarm: '#FFF7F0',
        surface: '#F7DCE3',
        surfaceSoft: '#FBE8ED',
        surfaceElevated: '#FFFAFB',
        card: '#FFF9FA',
        primary: '#EDBEC9',
        primaryHover: '#E7AEBE',
        primaryActive: '#D98FA4',
        primaryMuted: '#F7DCE3',
        accent: '#D98FA4',
        accentHover: '#CC7F96',
        accentActive: '#B96D84',
        text: '#4B343B',
        textSoft: '#6F545C',
        textMuted: '#967982',
        textInverse: '#FFF9FA',
        borderSoft: 'rgba(237, 190, 201, 0.42)',
        border: 'rgba(217, 143, 164, 0.28)',
        divider: 'rgba(75, 52, 59, 0.12)',
        success: '#7F9F83',
        successBg: '#EEF5EC',
        warning: '#C5A15D',
        warningBg: '#FFF3D8',
        error: '#BD6F78',
        errorBg: '#FDE7EA',
        info: '#7E9DAE',
        infoBg: '#EAF3F6',
        ivory: '#FFF7F0',
        paper: '#FFFAFB',
        ink: '#4B343B',
        rose: '#D98FA4',
        blush: '#F7DCE3',
        petal: '#EDBEC9',
        coral: '#e58f8f',
        sage: '#8fb79a',
        leaf: '#7fa88a',
        leafsoft: '#dfeede',
        skysoft: '#d6e6ea',
        honey: '#d6b76c',
      },
      fontFamily: {
        sans: [
          'Pretendard',
          'Apple SD Gothic Neo',
          'Noto Sans KR',
          'system-ui',
          'sans-serif',
        ],
        serif: [
          'Nanum Myeongjo',
          'AppleMyungjo',
          'Georgia',
          'serif',
        ],
        hand: [
          'AnniversaryHand',
          'Nanum Pen Script',
          'Apple SD Gothic Neo',
          'Bradley Hand',
          'Comic Sans MS',
          'cursive',
        ],
      },
      boxShadow: {
        soft: '0 12px 32px rgba(75, 52, 59, 0.08)',
        paper: '0 18px 44px rgba(126, 82, 94, 0.12)',
        photo: '0 18px 36px rgba(126, 82, 94, 0.14)',
        floating: '0 24px 64px rgba(126, 82, 94, 0.16)',
      },
    },
  },
  plugins: [],
};
